version: '3'
services:
  pg:
    image: 'bitnami/postgresql'
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=biblioteca_test